"""seeding data

Revision ID: 2cae3b20a4b0
Revises: 91d9c5fa7c68
Create Date: 2025-05-29 05:51:43.906938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cae3b20a4b0'
down_revision: Union[str, None] = '91d9c5fa7c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
