"""Added CLI with click functionality

Revision ID: 91d9c5fa7c68
Revises: 2eff7a703292
Create Date: 2025-05-29 05:30:06.549088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d9c5fa7c68'
down_revision: Union[str, None] = '2eff7a703292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
